event.o: event.c event.h
	gcc -c event.c
aepoll.o: aepoll.c aepoll.h
	gcc -c aepoll.c
tcpsocket.o: tcpsocket.c tcpsocket.h
	gcc -c tcpsocket.c
buffer.o: buffer.c buffer.h
	gcc -c buffer.c
conn.o: conn.c conn.h
	gcc -c conn.c
timer.o: timer.c timer.h
	gcc -c timer.c
codec.o: codec.c codec.h
	gcc -c codec.c
clean:
	rm -rf *.o *.gch
